apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: trajectory
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: 192.168.0.54:49153 # Required unless "server" field is set . Example: "mongo-mongodb.default.svc.cluster.local:27017"
  - name: username
    value: docker # Optional. Example: "admin"
  - name: password
    value: mongopw # Optional